/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppSettingsRouteRouteImport } from './routes/_app/settings/route'
import { Route as AuthForgotPasswordRouteImport } from './routes/_auth/forgot-password'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AuthRegisterRouteImport } from './routes/_auth/register'
import { Route as AppCashIndexRouteImport } from './routes/_app/cash/index'
import { Route as AppExpensesIndexRouteImport } from './routes/_app/expenses/index'
import { Route as AppInvoicesIndexRouteImport } from './routes/_app/invoices/index'
import { Route as AppOrdersIndexRouteImport } from './routes/_app/orders/index'
import { Route as AppOrdersNewRouteImport } from './routes/_app/orders/new'
import { Route as AppPosCounterRouteImport } from './routes/_app/pos/counter'
import { Route as AppReservationsIndexRouteImport } from './routes/_app/reservations/index'
import { Route as AppReservationsNewRouteImport } from './routes/_app/reservations/new'
import { Route as AppSalonIndexRouteImport } from './routes/_app/salon/index'
import { Route as AppSettingsDeliveryRouteImport } from './routes/_app/settings/delivery'
import { Route as AppSettingsFiscalRouteImport } from './routes/_app/settings/fiscal'
import { Route as AppSettingsMapRouteImport } from './routes/_app/settings/map'
import { Route as AppSettingsPrintingRouteImport } from './routes/_app/settings/printing'
import { Route as AppSettingsReservationsRouteImport } from './routes/_app/settings/reservations'
import { Route as AppSettingsRestaurantRouteImport } from './routes/_app/settings/restaurant'
import { Route as AppSuppliersIndexRouteImport } from './routes/_app/suppliers/index'
import { Route as AppSuppliersPurchaseOrdersRouteImport } from './routes/_app/suppliers/purchase-orders'
import { Route as AppInventoryIngredientsIndexRouteImport } from './routes/_app/inventory/ingredients/index'
import { Route as AppMenuProductsIndexRouteImport } from './routes/_app/menu/products/index'

const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSettingsRouteRoute = AppSettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRouteRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AppCashIndexRoute = AppCashIndexRouteImport.update({
  id: '/cash/',
  path: '/cash/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppExpensesIndexRoute = AppExpensesIndexRouteImport.update({
  id: '/expenses/',
  path: '/expenses/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppInvoicesIndexRoute = AppInvoicesIndexRouteImport.update({
  id: '/invoices/',
  path: '/invoices/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppOrdersIndexRoute = AppOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppOrdersNewRoute = AppOrdersNewRouteImport.update({
  id: '/orders/new',
  path: '/orders/new',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppPosCounterRoute = AppPosCounterRouteImport.update({
  id: '/pos/counter',
  path: '/pos/counter',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppReservationsIndexRoute = AppReservationsIndexRouteImport.update({
  id: '/reservations/',
  path: '/reservations/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppReservationsNewRoute = AppReservationsNewRouteImport.update({
  id: '/reservations/new',
  path: '/reservations/new',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSalonIndexRoute = AppSalonIndexRouteImport.update({
  id: '/salon/',
  path: '/salon/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSettingsDeliveryRoute = AppSettingsDeliveryRouteImport.update({
  id: '/delivery',
  path: '/delivery',
  getParentRoute: () => AppSettingsRouteRoute,
} as any)
const AppSettingsFiscalRoute = AppSettingsFiscalRouteImport.update({
  id: '/fiscal',
  path: '/fiscal',
  getParentRoute: () => AppSettingsRouteRoute,
} as any)
const AppSettingsMapRoute = AppSettingsMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => AppSettingsRouteRoute,
} as any)
const AppSettingsPrintingRoute = AppSettingsPrintingRouteImport.update({
  id: '/printing',
  path: '/printing',
  getParentRoute: () => AppSettingsRouteRoute,
} as any)
const AppSettingsReservationsRoute = AppSettingsReservationsRouteImport.update({
  id: '/reservations',
  path: '/reservations',
  getParentRoute: () => AppSettingsRouteRoute,
} as any)
const AppSettingsRestaurantRoute = AppSettingsRestaurantRouteImport.update({
  id: '/restaurant',
  path: '/restaurant',
  getParentRoute: () => AppSettingsRouteRoute,
} as any)
const AppSuppliersIndexRoute = AppSuppliersIndexRouteImport.update({
  id: '/suppliers/',
  path: '/suppliers/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSuppliersPurchaseOrdersRoute =
  AppSuppliersPurchaseOrdersRouteImport.update({
    id: '/suppliers/purchase-orders',
    path: '/suppliers/purchase-orders',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppInventoryIngredientsIndexRoute =
  AppInventoryIngredientsIndexRouteImport.update({
    id: '/inventory/ingredients/',
    path: '/inventory/ingredients/',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppMenuProductsIndexRoute = AppMenuProductsIndexRouteImport.update({
  id: '/menu/products/',
  path: '/menu/products/',
  getParentRoute: () => AppRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/settings': typeof AppSettingsRouteRouteWithChildren
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/orders/new': typeof AppOrdersNewRoute
  '/pos/counter': typeof AppPosCounterRoute
  '/reservations/new': typeof AppReservationsNewRoute
  '/settings/delivery': typeof AppSettingsDeliveryRoute
  '/settings/fiscal': typeof AppSettingsFiscalRoute
  '/settings/map': typeof AppSettingsMapRoute
  '/settings/printing': typeof AppSettingsPrintingRoute
  '/settings/reservations': typeof AppSettingsReservationsRoute
  '/settings/restaurant': typeof AppSettingsRestaurantRoute
  '/suppliers/purchase-orders': typeof AppSuppliersPurchaseOrdersRoute
  '/cash/': typeof AppCashIndexRoute
  '/expenses/': typeof AppExpensesIndexRoute
  '/invoices/': typeof AppInvoicesIndexRoute
  '/orders/': typeof AppOrdersIndexRoute
  '/reservations/': typeof AppReservationsIndexRoute
  '/salon/': typeof AppSalonIndexRoute
  '/suppliers/': typeof AppSuppliersIndexRoute
  '/inventory/ingredients/': typeof AppInventoryIngredientsIndexRoute
  '/menu/products/': typeof AppMenuProductsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/settings': typeof AppSettingsRouteRouteWithChildren
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/orders/new': typeof AppOrdersNewRoute
  '/pos/counter': typeof AppPosCounterRoute
  '/reservations/new': typeof AppReservationsNewRoute
  '/settings/delivery': typeof AppSettingsDeliveryRoute
  '/settings/fiscal': typeof AppSettingsFiscalRoute
  '/settings/map': typeof AppSettingsMapRoute
  '/settings/printing': typeof AppSettingsPrintingRoute
  '/settings/reservations': typeof AppSettingsReservationsRoute
  '/settings/restaurant': typeof AppSettingsRestaurantRoute
  '/suppliers/purchase-orders': typeof AppSuppliersPurchaseOrdersRoute
  '/cash': typeof AppCashIndexRoute
  '/expenses': typeof AppExpensesIndexRoute
  '/invoices': typeof AppInvoicesIndexRoute
  '/orders': typeof AppOrdersIndexRoute
  '/reservations': typeof AppReservationsIndexRoute
  '/salon': typeof AppSalonIndexRoute
  '/suppliers': typeof AppSuppliersIndexRoute
  '/inventory/ingredients': typeof AppInventoryIngredientsIndexRoute
  '/menu/products': typeof AppMenuProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteRouteWithChildren
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_app/settings': typeof AppSettingsRouteRouteWithChildren
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/_app/': typeof AppIndexRoute
  '/_app/orders/new': typeof AppOrdersNewRoute
  '/_app/pos/counter': typeof AppPosCounterRoute
  '/_app/reservations/new': typeof AppReservationsNewRoute
  '/_app/settings/delivery': typeof AppSettingsDeliveryRoute
  '/_app/settings/fiscal': typeof AppSettingsFiscalRoute
  '/_app/settings/map': typeof AppSettingsMapRoute
  '/_app/settings/printing': typeof AppSettingsPrintingRoute
  '/_app/settings/reservations': typeof AppSettingsReservationsRoute
  '/_app/settings/restaurant': typeof AppSettingsRestaurantRoute
  '/_app/suppliers/purchase-orders': typeof AppSuppliersPurchaseOrdersRoute
  '/_app/cash/': typeof AppCashIndexRoute
  '/_app/expenses/': typeof AppExpensesIndexRoute
  '/_app/invoices/': typeof AppInvoicesIndexRoute
  '/_app/orders/': typeof AppOrdersIndexRoute
  '/_app/reservations/': typeof AppReservationsIndexRoute
  '/_app/salon/': typeof AppSalonIndexRoute
  '/_app/suppliers/': typeof AppSuppliersIndexRoute
  '/_app/inventory/ingredients/': typeof AppInventoryIngredientsIndexRoute
  '/_app/menu/products/': typeof AppMenuProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/orders/new'
    | '/pos/counter'
    | '/reservations/new'
    | '/settings/delivery'
    | '/settings/fiscal'
    | '/settings/map'
    | '/settings/printing'
    | '/settings/reservations'
    | '/settings/restaurant'
    | '/suppliers/purchase-orders'
    | '/cash/'
    | '/expenses/'
    | '/invoices/'
    | '/orders/'
    | '/reservations/'
    | '/salon/'
    | '/suppliers/'
    | '/inventory/ingredients/'
    | '/menu/products/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/settings'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/orders/new'
    | '/pos/counter'
    | '/reservations/new'
    | '/settings/delivery'
    | '/settings/fiscal'
    | '/settings/map'
    | '/settings/printing'
    | '/settings/reservations'
    | '/settings/restaurant'
    | '/suppliers/purchase-orders'
    | '/cash'
    | '/expenses'
    | '/invoices'
    | '/orders'
    | '/reservations'
    | '/salon'
    | '/suppliers'
    | '/inventory/ingredients'
    | '/menu/products'
  id:
    | '__root__'
    | '/_app'
    | '/_auth'
    | '/_app/settings'
    | '/_auth/forgot-password'
    | '/_auth/login'
    | '/_auth/register'
    | '/_app/'
    | '/_app/orders/new'
    | '/_app/pos/counter'
    | '/_app/reservations/new'
    | '/_app/settings/delivery'
    | '/_app/settings/fiscal'
    | '/_app/settings/map'
    | '/_app/settings/printing'
    | '/_app/settings/reservations'
    | '/_app/settings/restaurant'
    | '/_app/suppliers/purchase-orders'
    | '/_app/cash/'
    | '/_app/expenses/'
    | '/_app/invoices/'
    | '/_app/orders/'
    | '/_app/reservations/'
    | '/_app/salon/'
    | '/_app/suppliers/'
    | '/_app/inventory/ingredients/'
    | '/_app/menu/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRouteRoute: typeof AppRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_app/cash/': {
      id: '/_app/cash/'
      path: '/cash'
      fullPath: '/cash/'
      preLoaderRoute: typeof AppCashIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/expenses/': {
      id: '/_app/expenses/'
      path: '/expenses'
      fullPath: '/expenses/'
      preLoaderRoute: typeof AppExpensesIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/invoices/': {
      id: '/_app/invoices/'
      path: '/invoices'
      fullPath: '/invoices/'
      preLoaderRoute: typeof AppInvoicesIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/orders/': {
      id: '/_app/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof AppOrdersIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/orders/new': {
      id: '/_app/orders/new'
      path: '/orders/new'
      fullPath: '/orders/new'
      preLoaderRoute: typeof AppOrdersNewRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/pos/counter': {
      id: '/_app/pos/counter'
      path: '/pos/counter'
      fullPath: '/pos/counter'
      preLoaderRoute: typeof AppPosCounterRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/reservations/': {
      id: '/_app/reservations/'
      path: '/reservations'
      fullPath: '/reservations/'
      preLoaderRoute: typeof AppReservationsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/reservations/new': {
      id: '/_app/reservations/new'
      path: '/reservations/new'
      fullPath: '/reservations/new'
      preLoaderRoute: typeof AppReservationsNewRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/salon/': {
      id: '/_app/salon/'
      path: '/salon'
      fullPath: '/salon/'
      preLoaderRoute: typeof AppSalonIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/settings/delivery': {
      id: '/_app/settings/delivery'
      path: '/delivery'
      fullPath: '/settings/delivery'
      preLoaderRoute: typeof AppSettingsDeliveryRouteImport
      parentRoute: typeof AppSettingsRouteRoute
    }
    '/_app/settings/fiscal': {
      id: '/_app/settings/fiscal'
      path: '/fiscal'
      fullPath: '/settings/fiscal'
      preLoaderRoute: typeof AppSettingsFiscalRouteImport
      parentRoute: typeof AppSettingsRouteRoute
    }
    '/_app/settings/map': {
      id: '/_app/settings/map'
      path: '/map'
      fullPath: '/settings/map'
      preLoaderRoute: typeof AppSettingsMapRouteImport
      parentRoute: typeof AppSettingsRouteRoute
    }
    '/_app/settings/printing': {
      id: '/_app/settings/printing'
      path: '/printing'
      fullPath: '/settings/printing'
      preLoaderRoute: typeof AppSettingsPrintingRouteImport
      parentRoute: typeof AppSettingsRouteRoute
    }
    '/_app/settings/reservations': {
      id: '/_app/settings/reservations'
      path: '/reservations'
      fullPath: '/settings/reservations'
      preLoaderRoute: typeof AppSettingsReservationsRouteImport
      parentRoute: typeof AppSettingsRouteRoute
    }
    '/_app/settings/restaurant': {
      id: '/_app/settings/restaurant'
      path: '/restaurant'
      fullPath: '/settings/restaurant'
      preLoaderRoute: typeof AppSettingsRestaurantRouteImport
      parentRoute: typeof AppSettingsRouteRoute
    }
    '/_app/suppliers/': {
      id: '/_app/suppliers/'
      path: '/suppliers'
      fullPath: '/suppliers/'
      preLoaderRoute: typeof AppSuppliersIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/suppliers/purchase-orders': {
      id: '/_app/suppliers/purchase-orders'
      path: '/suppliers/purchase-orders'
      fullPath: '/suppliers/purchase-orders'
      preLoaderRoute: typeof AppSuppliersPurchaseOrdersRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/inventory/ingredients/': {
      id: '/_app/inventory/ingredients/'
      path: '/inventory/ingredients'
      fullPath: '/inventory/ingredients/'
      preLoaderRoute: typeof AppInventoryIngredientsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/menu/products/': {
      id: '/_app/menu/products/'
      path: '/menu/products'
      fullPath: '/menu/products/'
      preLoaderRoute: typeof AppMenuProductsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppSettingsRouteRouteChildren {
  AppSettingsDeliveryRoute: typeof AppSettingsDeliveryRoute
  AppSettingsFiscalRoute: typeof AppSettingsFiscalRoute
  AppSettingsMapRoute: typeof AppSettingsMapRoute
  AppSettingsPrintingRoute: typeof AppSettingsPrintingRoute
  AppSettingsReservationsRoute: typeof AppSettingsReservationsRoute
  AppSettingsRestaurantRoute: typeof AppSettingsRestaurantRoute
}

const AppSettingsRouteRouteChildren: AppSettingsRouteRouteChildren = {
  AppSettingsDeliveryRoute: AppSettingsDeliveryRoute,
  AppSettingsFiscalRoute: AppSettingsFiscalRoute,
  AppSettingsMapRoute: AppSettingsMapRoute,
  AppSettingsPrintingRoute: AppSettingsPrintingRoute,
  AppSettingsReservationsRoute: AppSettingsReservationsRoute,
  AppSettingsRestaurantRoute: AppSettingsRestaurantRoute,
}

const AppSettingsRouteRouteWithChildren =
  AppSettingsRouteRoute._addFileChildren(AppSettingsRouteRouteChildren)

interface AppRouteRouteChildren {
  AppSettingsRouteRoute: typeof AppSettingsRouteRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
  AppOrdersNewRoute: typeof AppOrdersNewRoute
  AppPosCounterRoute: typeof AppPosCounterRoute
  AppReservationsNewRoute: typeof AppReservationsNewRoute
  AppSuppliersPurchaseOrdersRoute: typeof AppSuppliersPurchaseOrdersRoute
  AppCashIndexRoute: typeof AppCashIndexRoute
  AppExpensesIndexRoute: typeof AppExpensesIndexRoute
  AppInvoicesIndexRoute: typeof AppInvoicesIndexRoute
  AppOrdersIndexRoute: typeof AppOrdersIndexRoute
  AppReservationsIndexRoute: typeof AppReservationsIndexRoute
  AppSalonIndexRoute: typeof AppSalonIndexRoute
  AppSuppliersIndexRoute: typeof AppSuppliersIndexRoute
  AppInventoryIngredientsIndexRoute: typeof AppInventoryIngredientsIndexRoute
  AppMenuProductsIndexRoute: typeof AppMenuProductsIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppSettingsRouteRoute: AppSettingsRouteRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
  AppOrdersNewRoute: AppOrdersNewRoute,
  AppPosCounterRoute: AppPosCounterRoute,
  AppReservationsNewRoute: AppReservationsNewRoute,
  AppSuppliersPurchaseOrdersRoute: AppSuppliersPurchaseOrdersRoute,
  AppCashIndexRoute: AppCashIndexRoute,
  AppExpensesIndexRoute: AppExpensesIndexRoute,
  AppInvoicesIndexRoute: AppInvoicesIndexRoute,
  AppOrdersIndexRoute: AppOrdersIndexRoute,
  AppReservationsIndexRoute: AppReservationsIndexRoute,
  AppSalonIndexRoute: AppSalonIndexRoute,
  AppSuppliersIndexRoute: AppSuppliersIndexRoute,
  AppInventoryIngredientsIndexRoute: AppInventoryIngredientsIndexRoute,
  AppMenuProductsIndexRoute: AppMenuProductsIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRouteRoute: AppRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
